### ISSUE TITLE
Suggestion - Adding spark.driver.host to config

### ISSUE THREAD

**Issue by ctoledo-img-com-br** [mraad/spark-esri#1]
Hi Mansour,

I’d like to give a little suggestion.  Adding **"spark.driver.host":"127.0.0.1"** to the config variable as in the example below 

```
config = {"spark.driver.memory":"2G", "spark.driver.host":"127.0.0.1"}
spark = spark_start(config=config)
```

Will prevent from having SparkExceptions failing to connect to domain machine name and IP.  Took me some time before I figure it out what was causing and how to fix the error.

```
Py4JJavaError: An error occurred while calling o29.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.io.IOException: Failed to connect to NOTEXXXXX.XXX.LOCAL/192.168.0.XXX:51325
```

Carlos

**Comment by mraad** [comment]
Will add it - Thanks

**Comment by mraad** [comment]
Added :-)

**Comment by ctoledo-img-com-br** [comment]
You're welcome, glad to be of help.
